/*jslint node: true */
/**
 * The following Node.js file generates json files of
 * games played by ArtVark.  To run this on Warren's
 * current machine, copy this file to
 * C:\Users\Warren\chess-grab and run the following:
 *        node testnode.js
 *
 * The json files generated by this program then need
 * to be copied to ..\..\data.
 *
 * These files are named yYYYYmMM.json where YYYY
 * is the year and MM is the month.
 */
var ChessWebAPI = require("chess-web-api");

var fs = require("fs");

var chessAPI = new ChessWebAPI({
    queue: true
});

var printResults = function (response) {
    var games = response.body;
    if (games.games[0]) {
        var str_info = games.games[0].pgn;
        var scanned_info = str_info.indexOf("EndDate");
        var part_str = str_info.substr(scanned_info);
        var scan2 = part_str.indexOf("\"");
        var part_str2 = part_str.substr(scan2 + 1);
        var end_indx = part_str2.indexOf("\"");
        var date_str = part_str2.substr(0, end_indx);
        var date_parts = date_str.split(".");
        var y = date_parts[0];
        var i = date_parts[1];
        console.log(date_str);
        var outdata = JSON.stringify(response.body);
        var filev = `y${y}m${i}.json`;
        fs.writeFile(filev, outdata, function (err) {
            if (err) {
                console.log(err);
            }
        });
    }
};

var today = new Date();

var yyyy = today.getFullYear();
var mth = today.getMonth() + 1;

var nlist = Array.apply(null, {length: mth}).map(Number.call, Number);

function myFunc(index) {
    var m = index + 1;
    chessAPI.dispatch(
        chessAPI.getPlayerCompleteMonthlyArchives,
        printResults,
        ["ArtVark", yyyy, m]
    );
}

last_year = yyyy - 1;
chessAPI.dispatch(
    chessAPI.getPlayerCompleteMonthlyArchives,
    printResults,
    ["ArtVark", last_year, 12]
);
nlist.forEach(myFunc);